### ISSUE TITLE
More dungeon aliases

### ISSUE THREAD

**Issue by voxcati** [iopred/keystone#6]
Following up on #5, I would recommend adding the following aliases to the current lists, based on errors I've seen on my guild's Discord server:

AD: `"ataldazar", "atal'dazar"`

FH: `"freehold"`

KR: `"kings rest", "king's rest"`

TD: `"tol dagor"`

WM: `"waycrest manor"`

Thank you!

**Comment by iopred** [comment]
This should be done now, sorry!

**Comment by voxcati** [comment]
Hey, thanks! :)
