### ISSUE TITLE
Commonly used aliases request

### ISSUE THREAD

**Issue by JakubSmahovsky** [iopred/keystone#8]
Could you add a couple often used aliases to the lists? We're using this on our discord and people keep trying the wrong shortcuts 😄, namely:
"ml" for The MOTHERLODE
"work", "workshop" for Operation Mechagon: Workshop
"junk", "yard", "junkyard" for Operation Mechagon: Junkyard
Or if you'd prefer, you can give me access and I'll make a PR for you.

**Comment by iopred** [comment]
Make the PR and i'll merge it immediately, thank you!
